[model]
J = 1.0
L = 16
hx = 1.0
hz = 0.5
name = "TransverseIsing1D"
pbc = false

[dmrg]
overlap_penalty = 10
states = 1
sweeps = [
  {"maxdim" = 50, "mindim" = 1, "cutoff" = 1e-6, "noise" = 1e-7},
  {"maxdim" = 80, "mindim" = 1, "cutoff" = 1e-8, "noise" = 1e-8},
  {"maxdim" = 100, "mindim" = 1, "cutoff" = 1e-10, "noise" = 1e-9},
  {"maxdim" = 150, "mindim" = 1, "cutoff" = 1e-12, "noise" = 1e-10},
  {"maxdim" = 200, "mindim" = 1, "cutoff" = 1e-12, "noise" = 1e-11},
  {"maxdim" = 250, "mindim" = 1, "cutoff" = 1e-12, "noise" = 1e-12},
  {"maxdim" = 300, "mindim" = 1, "cutoff" = 0.0, "noise" = 0.0},
  {"maxdim" = 500, "mindim" = 1, "cutoff" = 0.0, "noise" = 0.0},
]
