name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - ${{ matrix.version }}
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2
      - name: Install julia.
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
      - name: Build package.
        uses: julia-actions/julia-buildpkg@latest
      - name: Run TransverseIsing1D example.
        run: julia --project=. src/DMRG.jl -i examples/TransverseIsing1D.toml
